import RaceCard from "@/components/RaceCard";
import { Button } from "@/components/ui/button";
import { ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";
import { useState, useEffect } from "react";
import { Skeleton } from "@/components/ui/skeleton";

interface RaceItem {
  id: number;
    title: string;
      track: string;
        date: string;
          time: string;
            image?: string;
              laps?: string;
                duration?: string;
                  pilots: number;
                    participants?: { username: string; registeredAt: string }[];
                    }

                    const RacesSection = () => {
                      const [races, setRaces] = useState<RaceItem[]>([]);
                        const [loading, setLoading] = useState(true);

                          useEffect(() => {
                              fetch('/api/races')
                                    .then(res => res.json())
                                          .then(data => {
                                                  // Take first 3 races
                                                          setRaces(data.slice(0, 3));
                                                                  setLoading(false);
                                                                        })
                                                                              .catch(err => {
                                                                                      console.error('Failed to fetch races:', err);
                                                                                              setLoading(false);
                                                                                                    });
                                                                                                      }, []);

                                                                                                        if (loading) {
                                                                                                            return (
                                                                                                                  <section id="corridas" className="py-24">
                                                                                                                          <div className="container">
                                                                                                                                    <div className="mb-12 flex flex-col items-start justify-between gap-4 md:flex-row md:items-end">
                                                                                                                                                <div>
                                                                                                                                                              <span className="mb-2 inline-block font-heading text-sm font-bold uppercase tracking-wider text-primary">
                                                                                                                                                                              Agenda
                                                                                                                                                                                            </span>
                                                                                                                                                                                                          <h2 className="font-heading text-3xl font-bold md:text-4xl">
                                                                                                                                                                                                                          Próximas Corridas
                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                    {Array.from({ length: 3 }).map((_, i) => (
                                                                                                                                                                                                                                                                                                  <div key={i}>
                                                                                                                                                                                                                                                                                                                  <Skeleton className="aspect-video w-full rounded-lg mb-4" />
                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-6 w-full mb-2" />
                                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-4 w-3/4 mb-4" />
                                                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-4 w-full" />
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                <section id="corridas" className="py-24">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mb-12 flex flex-col items-start justify-between gap-4 md:flex-row md:items-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="mb-2 inline-block font-heading text-sm font-bold uppercase tracking-wider text-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Agenda
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="font-heading text-3xl font-bold md:text-4xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Próximas Corridas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button variant="ghost" className="group text-muted-foreground hover:text-foreground" asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/races">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Ver todas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {races.map((race, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={race.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="animate-fade-in"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ animationDelay: `${index * 0.1}s` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <RaceCard {...race} id={String(race.id)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default RacesSection;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          